<?php
// autoload.php @generated by Composer
if (version_compare(PHP_VERSION, "7.0", ">=")) {
    require_once __DIR__ . '/php7/composer/autoload_real.php';
    return ComposerAutoloaderInit15e1bb190deb7e0de5800f7ba6beb656::getLoader();
} else {
    require_once __DIR__ . '/php5/composer' . '/autoload_real.php';
    return ComposerAutoloaderInitabb2d816ab1c43c19957a53c76389874::getLoader();
}
